org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties

minecraft_version=1.21.1
fabric_version=0.115.4+1.21.1
loader_version=0.16.13

## Mod Properties

mod_id=lolmst
mod_name=More Smithing Tables
mod_comp_name=MoreSmithingTables
mod_license=MIT
mod_version=1.3.0
mod_group_id=de.pnku.mst
mod_authors=pnku, LieOnLion
mod_description=Adding smithing table variants to Minecraft

# Quad Properties
quad_version=1.2.0